FROM centos6.6:latest

MAINTAINER yanxinyue

RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm && rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm

RUN yum install -y php56w php56w-gd php56w-mysql curl curl-devel php56w-xml 

EXPOSE 80

CMD /usr/sbin/httpd -D FOREGROUND
